### ISSUE TITLE
Add rate limiting

### ISSUE THREAD

**Issue by ezzcodeezzlife** [zoelake/travelbug#1]
In order to protect your precious 18$ of free openai api credit you should add rate limiting to you application. 

I used [this example](https://github.com/vercel/next.js/tree/canary/examples/api-routes-rate-limit) in [my application](https://github.com/ezzcodeezzlife/openaiwebsite) and it works great!

Have fun coding! 😊

**Comment by zoelake** [comment]
Almost a year later, but I just implemented this- thank you for the advice! :)
